"""add active_execution_id to device_states

Revision ID: 7c353118861b
Revises: 97789ba91e84
Create Date: 2026-04-05 06:51:01.119388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c353118861b'
down_revision: Union[str, Sequence[str], None] = '97789ba91e84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_states', sa.Column('active_execution_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device_states', 'active_execution_id')
    # ### end Alembic commands ###
