"""
IEC 60945:2002 海事導航與無線電通訊設備標準
- Fourth edition 2002-08
- 適用設備類型：Portable（攜帶式）、Protected（防護式）、Exposed（暴露式）

測試條件來源：Table 3 – Durability and resistance to environmental conditions

ramp_rate：
  ✅ 法規未明確規定，取 1°C/min
  ✅ Damp heat：法規規定 3h ± 0.5h 升溫至 40°C，非獨立速率，暫用 1.0
"""

from ._base import steps_single_temp, steps_cycle

TREE = {
    "label": "IEC 60945 海事導航與無線電通訊設備",
    "description": "適用於海事導航與無線電通訊設備之環境耐久性測試。依 IEC 60945:2002 Table 3 定義。",
    "versions": {
        "IEC 60945:2002": {
            "label": "IEC 60945:2002（第四版）",
            "description": "定義 Portable、Protected、Exposed、Submerged 四種設備類型之環境測試條件。",
            "tests": {
                "Dry_Heat_Storage_+70": {
                    "sop_id": "iec60945_ba_+70_16h",
                    "name": "乾熱儲存 Test Ba：+70°C，16h（非通電，Portable / Exposed）",
                    "test_type": "chamber",
                    "version": "IEC 60945:2002",
                    "description": "高溫儲存測試。+70°C 持續 16 小時，非通電狀態，模擬船艙或太陽直曬環境下的儲存條件。適用於 Portable 與 Exposed 設備。",
                    "high_temperature": 70.0,
                    "low_temperature": None,
                    "target_temperature": 70.0,
                    "ramp_rate": 1.0,
                    "dwell_time_hours": 16,
                    "cycles": 1,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": False,
                    "temp_tolerance": 3.0,
                    "humi_tolerance": 5.0,
                    "reference": "IEC 60945:2002 Table 3 Dry Heat + Section 8.2.1",
                    "steps": steps_single_temp(70.0, 16, "high"),
                },
                "Dry_Heat_Functional_+55": {
                    "sop_id": "iec60945_bb_+55_16h",
                    "name": "乾熱工作 Test Bb：+55°C，16h（通電，Portable / Protected / Exposed）",
                    "test_type": "chamber",
                    "version": "IEC 60945:2002",
                    "description": "高溫功能測試。+55°C 持續 10~16 小時，通電工作狀態，評估設備在高溫環境下的電氣功能性。",
                    "high_temperature": 55.0,
                    "low_temperature": None,
                    "target_temperature": 55.0,
                    "ramp_rate": 1.0,
                    "dwell_time_hours": 16,
                    "cycles": 1,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": True,
                    "temp_tolerance": 3.0,
                    "humi_tolerance": 5.0,
                    "reference": "IEC 60945:2002 Table 3 Dry Heat + Section 8.2.2",
                    "steps": steps_single_temp(55.0, 16, "high"),
                },
                "Damp_Heat_+40_93RH": {
                    "sop_id": "iec60945_db_+40_16h_93rh",
                    "name": "濕熱 Test Db variant 1：+40°C，16h，93%RH（通電）",
                    "test_type": "chamber",
                    "version": "IEC 60945:2002",
                    "description": "濕熱功能測試。+40°C / 93%RH，3h 升溫，持續 10~16 小時，通電工作狀態。依 IEC 60068-2-30 Test Db variant 1 執行。1 cycle。",
                    "high_temperature": 40.0,
                    "low_temperature": None,
                    "target_temperature": 40.0,
                    "ramp_rate": 1.0,
                    "dwell_time_hours": 16,
                    "cycles": 1,
                    "humidity_rh_percent": 93.0,
                    "humidity_control": True,
                    "power_on": True,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 3.0,
                    "reference": "IEC 60945:2002 Table 3 Damp Heat + Section 8.3 + IEC 60068-2-30 Db variant 1",
                    "steps": steps_single_temp(40.0, 16, "high"),
                },
                "Cold_Portable_-20_Functional": {
                    "sop_id": "iec60945_ad_-20_16h",
                    "name": "低溫工作 Test Ad：-20°C，16h（通電，Portable）",
                    "test_type": "chamber",
                    "version": "IEC 60945:2002",
                    "description": "低溫功能測試（攜帶式設備）。-20°C 持續 10~16 小時，通電工作狀態。評估設備在低溫環境下的啟動與運作能力。",
                    "high_temperature": None,
                    "low_temperature": -20.0,
                    "target_temperature": -20.0,
                    "ramp_rate": 1.0,
                    "dwell_time_hours": 16,
                    "cycles": 1,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": True,
                    "temp_tolerance": 3.0,
                    "humi_tolerance": 5.0,
                    "reference": "IEC 60945:2002 Table 3 Low Temperature + Section 8.4.2",
                    "steps": steps_single_temp(-20.0, 16, "low"),
                },
                "Cold_Portable_-30_Storage": {
                    "sop_id": "iec60945_ab_-30_16h",
                    "name": "低溫儲存 Test Ab：-30°C，16h（非通電，Portable）",
                    "test_type": "chamber",
                    "version": "IEC 60945:2002",
                    "description": "低溫儲存測試（攜帶式設備）。-30°C 持續 10~16 小時，非通電狀態。",
                    "high_temperature": None,
                    "low_temperature": -30.0,
                    "target_temperature": -30.0,
                    "ramp_rate": 1.0,
                    "dwell_time_hours": 16,
                    "cycles": 1,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": False,
                    "temp_tolerance": 3.0,
                    "humi_tolerance": 5.0,
                    "reference": "IEC 60945:2002 Table 3 Low Temperature + Section 8.4.1",
                    "steps": steps_single_temp(-30.0, 16, "low"),
                },
                "Cold_Protected_-15": {
                    "sop_id": "iec60945_ab_-15_16h",
                    "name": "低溫 Test Ab：-15°C，16h（非通電，Protected）",
                    "test_type": "chamber",
                    "version": "IEC 60945:2002",
                    "description": "低溫測試（防護式設備）。-15°C 持續 10~16 小時，非通電狀態。",
                    "high_temperature": None,
                    "low_temperature": -15.0,
                    "target_temperature": -15.0,
                    "ramp_rate": 1.0,
                    "dwell_time_hours": 16,
                    "cycles": 1,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": False,
                    "temp_tolerance": 3.0,
                    "humi_tolerance": 5.0,
                    "reference": "IEC 60945:2002 Table 3 Low Temperature Protected",
                    "steps": steps_single_temp(-15.0, 16, "low"),
                },
                "Cold_Exposed_-25": {
                    "sop_id": "iec60945_ab_-25_16h",
                    "name": "低溫 Test Ab：-25°C，16h（非通電，Exposed）",
                    "test_type": "chamber",
                    "version": "IEC 60945:2002",
                    "description": "低溫測試（暴露式設備）。-25°C 持續 10~16 小時，非通電狀態。",
                    "high_temperature": None,
                    "low_temperature": -25.0,
                    "target_temperature": -25.0,
                    "ramp_rate": 1.0,
                    "dwell_time_hours": 16,
                    "cycles": 1,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": False,
                    "temp_tolerance": 3.0,
                    "humi_tolerance": 5.0,
                    "reference": "IEC 60945:2002 Table 3 Low Temperature Exposed",
                    "steps": steps_single_temp(-25.0, 16, "low"),
                },
            },
        },
    },
}
