"""
NMEA / IEC 61162 航海電子設備標準
ramp_rate：✅ IEC 60945:2002 Sec.8.1 明文：1°C/min
"""

from ._base import steps_single_temp, steps_cycle

TREE = {
    "label": "NMEA / IEC 61162 航海電子設備",
    "description": "NMEA 0183/2000 對應 IEC 61162-1/3。航海電子設備須通過 IEC 60945 通用要求，含高溫/低溫/濕熱測試。",
    "versions": {
        "IEC 61162-1:2016 / IEC 60945 (NMEA 0183)": {
            "label": "IEC 61162-1:2016 / IEC 60945（NMEA 0183，現行版）",
            "description": "NMEA 0183 單向串列通訊設備。環境測試依 IEC 60945:2002 執行。溫度範圍 -15°C ~ +55°C（暴露裝置至 +70°C）。",
            "tests": {
                "Dry_Heat_+55_Protected": {
                    "sop_id": "nmea_0183_dry_+55",
                    "name": "高溫工作：+55°C，16h（受保護裝置）",
                    "test_type": "chamber",
                    "version": "IEC 61162-1:2016 / IEC 60945",
                    "description": "受保護安裝（橋樓室內），工作溫度上限 +55°C，依 IEC 60068-2-2 Test Bb 執行，通電狀態。",
                    "high_temperature": 55.0,
                    "low_temperature": None,
                    "target_temperature": 55.0,
                    "ramp_rate": 1.0,  # ✅ IEC 60945:2002 Sec.8.1 明文：1°C/min
                    "dwell_time_hours": 16,
                    "cycles": 1,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": True,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 5.0,
                    "reference": "IEC 60945:2002 Sec.8.1 + IEC 61162-1:2016",
                    "steps": steps_single_temp(55.0, 16, "high"),
                },
                "Dry_Heat_+70_Exposed": {
                    "sop_id": "nmea_0183_dry_+70",
                    "name": "高溫工作：+70°C，16h（暴露裝置）",
                    "test_type": "chamber",
                    "version": "IEC 61162-1:2016 / IEC 60945",
                    "description": "暴露安裝（甲板/橋樓外部），工作溫度上限 +70°C，依 IEC 60068-2-2 Test Bb 執行，通電狀態。",
                    "high_temperature": 70.0,
                    "low_temperature": None,
                    "target_temperature": 70.0,
                    "ramp_rate": 1.0,
                    "dwell_time_hours": 16,
                    "cycles": 1,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": True,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 5.0,
                    "reference": "IEC 60945:2002 Sec.8.1 + IEC 61162-1:2016",
                    "steps": steps_single_temp(70.0, 16, "high"),
                },
                "Cold_-15": {
                    "sop_id": "nmea_0183_cold_-15",
                    "name": "低溫儲存：-15°C，16h",
                    "test_type": "chamber",
                    "version": "IEC 61162-1:2016 / IEC 60945",
                    "description": "航海電子設備低溫儲存，-15°C 持續 16 小時，非通電。",
                    "high_temperature": None,
                    "low_temperature": -15.0,
                    "target_temperature": -15.0,
                    "ramp_rate": 1.0,
                    "dwell_time_hours": 16,
                    "cycles": 1,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": False,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 5.0,
                    "reference": "IEC 60945:2002 Sec.8.4 + IEC 61162-1:2016",
                    "steps": steps_single_temp(-15.0, 16, "low"),
                },
                "Damp_Heat": {
                    "sop_id": "nmea_0183_damp",
                    "name": "濕熱穩態：+40°C，93%RH，16h（IEC 60945 單循環）",
                    "test_type": "chamber",
                    "version": "IEC 61162-1:2016 / IEC 60945",
                    "description": "航海電子設備濕熱測試，+40°C，93%RH，持續 10~16 小時（IEC 60945 Sec.8.3 單循環）。",
                    "high_temperature": 40.0,
                    "low_temperature": None,
                    "target_temperature": 40.0,
                    "ramp_rate": 1.0,
                    "dwell_time_hours": 16,
                    "cycles": 1,
                    "humidity_rh_percent": 93.0,
                    "humidity_control": True,
                    "power_on": False,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 5.0,
                    "reference": "IEC 60945:2002 Sec.8.3 + IEC 61162-1:2016",
                    "steps": steps_single_temp(40.0, 16, "high"),
                },
                "Temp_Cycle": {
                    "sop_id": "nmea_0183_cycle",
                    "name": "溫度循環：-15°C ↔ +55°C，3 循環",
                    "test_type": "chamber",
                    "version": "IEC 61162-1:2016 / IEC 60945",
                    "description": "航海電子設備溫度循環，模擬航行中溫度變化，3 循環，每端停留 60 分鐘。",
                    "high_temperature": 55.0,
                    "low_temperature": -15.0,
                    "target_temperature": 55.0,
                    "ramp_rate": 1.0,
                    "dwell_time_hours": 1,
                    "cycles": 3,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": False,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 5.0,
                    "reference": "IEC 60945:2002 + IEC 60068-2-14 Test Nb",
                    "steps": steps_cycle(-15.0, 55.0, 3),
                },
            },
        },
        "IEC 61162-3:2010 / IEC 60945 (NMEA 2000)": {
            "label": "IEC 61162-3:2010 / IEC 60945（NMEA 2000，現行版）",
            "description": "NMEA 2000 雙向網路通訊，適用於現代整合船用系統（CAN bus）。環境測試同 IEC 60945 要求。",
            "tests": {
                "Dry_Heat_+55": {
                    "sop_id": "nmea_2000_dry_+55",
                    "name": "高溫工作：+55°C，16h（受保護裝置）",
                    "test_type": "chamber",
                    "version": "IEC 61162-3:2010 / IEC 60945",
                    "description": "NMEA 2000 網路設備高溫工作測試，+55°C 持續 16 小時，通電狀態。",
                    "high_temperature": 55.0,
                    "low_temperature": None,
                    "target_temperature": 55.0,
                    "ramp_rate": 1.0,
                    "dwell_time_hours": 16,
                    "cycles": 1,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": True,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 5.0,
                    "reference": "IEC 60945:2002 + IEC 61162-3:2010",
                    "steps": steps_single_temp(55.0, 16, "high"),
                },
                "Cold_-15": {
                    "sop_id": "nmea_2000_cold_-15",
                    "name": "低溫儲存：-15°C，16h",
                    "test_type": "chamber",
                    "version": "IEC 61162-3:2010 / IEC 60945",
                    "description": "NMEA 2000 網路設備低溫儲存測試，-15°C 持續 16 小時，非通電。",
                    "high_temperature": None,
                    "low_temperature": -15.0,
                    "target_temperature": -15.0,
                    "ramp_rate": 1.0,
                    "dwell_time_hours": 16,
                    "cycles": 1,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": False,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 5.0,
                    "reference": "IEC 60945:2002 + IEC 61162-3:2010",
                    "steps": steps_single_temp(-15.0, 16, "low"),
                },
            },
        },
    },
}
